GET http://localhost:3000 HTTP/1.1

### articles
#### no query params
GET http://localhost:3000/articles HTTP/1.1

### with query params
GET http://localhost:3000/articles?type=json&amount=2 HTTP/1.1

#### Large Text File Stream
GET http://localhost:3000/largeTextFile HTTP/1.1
#### Sample Post Req
POST http://localhost:3000 HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
